
smb:
  - packages/smb/**

apollo-server:
  - packages/apollo-server/**

lifetime-legal:
  - packages/lifetime-legal/**

config-manager:
  - packages/config-manager/**

cognito-auth:
  - packages/cognito-auth/**
