# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

jobs:
  - job: buildWebApp
    displayName: Test and build web app
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - group: aws
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: yarn install
        displayName: Install deps
        failOnStderr: true
        env:
          NPM_TOKEN: $(NPM_TOKEN)

      - bash: printenv > src/constants/.env
        displayName: Injects ENVs
        env:
          COGNITO_CLIENT_ID: $(COGNITO_CLIENT_ID)
          COGNITO_USERPOOL_ID: $(COGNITO_USERPOOL_ID)
          MARKETPLACE_API_KEY: $(MARKETPLACE_API_KEY)
          REAPIT_API_KEY: $(REAPIT_API_KEY)

      - script: yarn test:ci
        displayName: Unit tests
        env:
          NPM_TOKEN: $(NPM_TOKEN)

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/.jest-junit-reports' # Optional
          mergeTestResults: false # Optional
          failTaskOnFailedTests: true # Optional
          publishRunAttachments: true # Optional

      - script: yarn build
        displayName: Build static assets
        failOnStderr: true
        env:
          NPM_TOKEN: $(NPM_TOKEN)

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/public/dist
          artifact: AppBundle

  - deployment: S3DeployWebDev
    displayName: 'Dev | S3 Deployment'
    dependsOn: buildWebApp
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'reapit-aml-checklist-dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: S3Upload@1
              displayName: Deploy assets to S3
              inputs:
                awsCredentials: 'df-huy'
                regionName: 'eu-west-2'
                bucketName: 'reapit-aml-checklist-dev'
                sourceFolder: '$(Pipeline.Workspace)/AppBundle'
                globExpressions: '**'
                filesAcl: 'public-read'
                createBucket: true

  - deployment: S3DeployWebProd
    displayName: 'Prod | S3 Deployment'
    dependsOn: buildWebApp
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/AC-'))
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'reapit-aml-checklist-prod'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: S3Upload@1
              displayName: Deploy assets to S3
              inputs:
                awsCredentials: 'df-huy'
                regionName: 'eu-west-2'
                bucketName: 'reapit-aml-checklist-prod'
                sourceFolder: '$(Pipeline.Workspace)/AppBundle'
                globExpressions: '**'
                filesAcl: 'public-read'
                createBucket: true
