# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: yarn install

- script: yarn test:ci

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/.jest-junit-reports' # Optional
    mergeTestResults: false # Optional
    failTaskOnFailedTests: true # Optional
    publishRunAttachments: true # Optional

- script: yarn build

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/public/dist
    artifact: AppStoreBundle
