# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: aws

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: yarn install

- bash: printenv > src/constants/.env
  env:
    COGNITO_CLIENT_ID: $(COGNITO_CLIENT_ID)
    COGNITO_USERPOOL_ID: $(COGNITO_USERPOOL_ID)
    MARKETPLACE_API_KEY: $(MARKETPLACE_API_KEY)
    REAPIT_API_KEY: $(REAPIT_API_KEY)

- script: yarn test:ci

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/.jest-junit-reports' # Optional
    mergeTestResults: false # Optional
    failTaskOnFailedTests: true # Optional
    publishRunAttachments: true # Optional

- script: yarn test-e2e:ci

- script: yarn build

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/public/dist
    artifact: AppStoreBundle
