service: cognito-auth-api-dev
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
custom: ${file(./env.yml)}
functions:
  api:
    handler: public/app.apiHandler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  mailer:
    handler: public/app.mailHandler
    events:
      - cognitoUserPool:
        pool: ${self:custom.COGNITO_USERPOOL_ID}
        trigger: CustomMessage
        existing: true