name: Release master

on:
  push:
    branches:
      - master


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environement
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
  
      - name: Check version
        run: yarn checkVersion

      - name: Make sure testcases passed
        run: yarn test

      - name: Make sure code don't have linter errors
        run: yarn lint

  create_release_in_github:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environement
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get installed node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-${{ hashFiles('**/yarn.lock') }}
      
      - run: yarn release:master
  
  publish_package_to_npm:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environement
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get installed node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: npm run build:npm

      - name: Publish project
        run: npm publish

  publish_package_to_cdn:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environement
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get installed node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: npm run build:cdn

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist-cdn'

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
